name: "Bump Tag"
description: "Bump and push git tag on merge"
author: "nogsantos"
runs:
  using: "docker"
  image: "Dockerfile"
outputs:
  new_tag:
    description: "Generated new tag"
  tag:
    description: "The latest tag after running this action"
  part:
    description: "The part of version which was bumped"
branding:
  icon: "git-merge"
  color: "yellow"
